// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlOW_XuwdBtmJsuXq3YKTP-9RAPxposBY',
    appId: '1:3454180745:web:0c62d82b6aaeb9d20a5558',
    messagingSenderId: '3454180745',
    projectId: 'eduattend-c3e03',
    authDomain: 'eduattend-c3e03.firebaseapp.com',
    storageBucket: 'eduattend-c3e03.firebasestorage.app',
    measurementId: 'G-13NGQT3JH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnc4INgsxIDBitiwSmkNvhFkXw9ZOrCoY',
    appId: '1:3454180745:android:6a1a7315cbf793830a5558',
    messagingSenderId: '3454180745',
    projectId: 'eduattend-c3e03',
    storageBucket: 'eduattend-c3e03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPZ8qrDy6mE8srgdGSvaLOK4c-KgGAyUU',
    appId: '1:3454180745:ios:1c71c7428280bfb90a5558',
    messagingSenderId: '3454180745',
    projectId: 'eduattend-c3e03',
    storageBucket: 'eduattend-c3e03.firebasestorage.app',
    iosBundleId: 'com.team9.eduattend.mobileAppProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPZ8qrDy6mE8srgdGSvaLOK4c-KgGAyUU',
    appId: '1:3454180745:ios:1c71c7428280bfb90a5558',
    messagingSenderId: '3454180745',
    projectId: 'eduattend-c3e03',
    storageBucket: 'eduattend-c3e03.firebasestorage.app',
    iosBundleId: 'com.team9.eduattend.mobileAppProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlOW_XuwdBtmJsuXq3YKTP-9RAPxposBY',
    appId: '1:3454180745:web:50229b2cb0d017780a5558',
    messagingSenderId: '3454180745',
    projectId: 'eduattend-c3e03',
    authDomain: 'eduattend-c3e03.firebaseapp.com',
    storageBucket: 'eduattend-c3e03.firebasestorage.app',
    measurementId: 'G-1ML8XHP5XK',
  );
}
