# Student table is keyed by Firebase Auth UID.
type Student @table{
  id: String! @default(expr: "auth.uid")
  email: String! @col(name: "email", dataType: "varchar(50)")
  name: String! @col(name: "name", dataType: "varchar(50)")
}

type Instructor @table {
  id: String! @default(expr: "auth.uid")
  email: String! @col(name: "email", dataType: "varchar(50)")
  name: String! @col(name: "name", dataType: "varchar(50)")
}

type Group @table {
  subject: Subject! 
  day: String! @col(name: "day",)
  startTime: String! @col(name: "starts_at",)
  endTime: String! @col(name: "ends_at",)
  students: Student! @unique
}

type Subject @table {
  teachedBy: Instructor! 
  subjectCode: String! @col(name: "code", dataType: "varchar(6)") @unique
  name: String! @col(name: "subject", dataType: "varchar(50)")
  student: Student!
}

type Attendance @table {
  group: Group!  
  student: Student!  
  status: String! @col(name: "status")
  attendanceDate: Timestamp @col(name: "Ddte") @default(expr: "request.time")
}   